// frontend/src/views/Home.vue
<template>
  <div class="home">
    <!-- 头部 -->
    <header>
      <h1>VanSour Image</h1>
      <p class="subtitle">简单快速的图片托管服务</p>
      <div class="header-actions">
        <div v-if="user" class="user-info">
          <span>{{ user.username }}</span>
          <button @click="showProfile = true" class="btn-profile" :aria-label="'打开个人资料'">
            个人资料
          </button>
          <button v-if="user.role === 'admin'" @click="showAdminPanel = true" class="btn-admin" :aria-label="'打开管理面板'">
            管理
          </button>
          <button @click="router.push('/settings')" class="btn-settings" :aria-label="'打开设置'">
            设置
          </button>
          <button @click="handleLogout" class="btn-logout" :aria-label="'退出登录'">
            退出
          </button>
        </div>
        <button @click="toggleTheme" class="btn-theme" :title="theme === 'dark' ? '切换亮色模式' : '切换暗色模式'" :aria-label="'切换主题'">
          {{ theme === 'dark' ? '🌙' : '☀️' }}
        </button>
      </div>
    </header>

    <!-- 未认证状态 -->
    <div v-if="!authenticated" class="unauth">
      <Auth @success="handleAuthSuccess" />
    </div>

    <!-- 已认证状态 -->
    <template v-else>
      <!-- 工具栏 -->
      <div class="toolbar">
        <div class="search-box">
          <input
            v-model="searchQuery"
            placeholder="搜索图片名称..."
            @input="handleSearchInput"
            :aria-label="'搜索图片'"
            :disabled="loading"
          />
          <select v-model="sortBy" @change="handleSortChange" class="sort-select" :aria-label="'排序方式'">
            <option value="created_at">上传时间</option>
            <option value="views">浏览量</option>
            <option value="size">大小</option>
          </select>
          <select v-model="sortOrder" @change="handleSortChange" class="sort-order" :aria-label="'排序顺序'">
            <option value="DESC">降序</option>
            <option value="ASC">升序</option>
          </select>
          <select v-model="selectedCategory" @change="handleSortChange" class="category-select" :aria-label="'选择分类'">
            <option value="">全部分类</option>
            <option v-for="cat in categories" :key="cat.id" :value="cat.id">{{ cat.name }}</option>
          </select>
        </div>
      </div>

      <!-- 上传区域 -->
      <div class="upload-section">
        <UploadZone ref="uploadZoneRef" @upload="handleUpload" :uploading="uploading" />
      </div>

      <!-- 图片列表 -->
      <ImageList
        :images="images"
        :totalImages="pagination.total"
        :categories="categories"
        :refreshTrigger="refreshTrigger"
        :loading="isLoading"
        @preview="handlePreview"
        @edit="handleEdit"
        @rename="handleRename"
        @setExpiry="handleSetExpiry"
        @update="handleUpdate"
        @delete="handleDelete"
        @duplicate="handleDuplicate"
      />
    </template>

    <!-- 图片预览 -->
    <ImagePreview
      :visible="preview.visible"
      :image="preview.image"
      @close="preview.visible = false"
      @toast="showToast"
    />

    <!-- 回收站 -->
    <Trash :refreshTrigger="refreshTrigger" @refresh="handleTrashRefresh" />

    <!-- 分类管理 -->
    <CategoryModal
      :visible="showCategoryModal"
      @close="showCategoryModal = false"
      @error="showToast"
      @created="handleCategoryCreated"
    />

    <!-- 图片编辑器 -->
    <ImageEditor
      v-if="showEditor && editingImage"
      :visible="showEditor"
      :image="editingImage"
      @close="showEditor = false"
      @applied="handleEditApplied"
    />

    <!-- 管理面板 -->
    <AdminPanel
      v-if="showAdminPanel"
      :visible="showAdminPanel"
      @close="showAdminPanel = false"
    />

    <!-- 个人资料 -->
    <Profile
      v-if="showProfile"
      @close="showProfile = false"
      @toast="showToast"
    />

    <!-- 全局 Toast -->
    <Toast ref="toastRef" />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { auth, api } from '../store/auth'
import { setGlobalToast, toastSuccess, toastError } from '../composables/useToast'
import { debounce } from '../utils/debounce'
import { showConfirm } from '../composables/useDialog'
import { validateImageFile } from '../utils/validation'
import type {
  Image,
  Category,
  Pagination,
  ToastType
} from '../types'
import * as CONSTANTS from '../constants'

// 组件导入
import UploadZone from '../components/UploadZone.vue'
import ImageList from '../components/ImageList.vue'
import ImagePreview from '../components/ImagePreview.vue'
import Trash from '../components/Trash.vue'
import Toast from '../components/Toast.vue'
import CategoryModal from '../components/CategoryModal.vue'
import ImageEditor from '../components/ImageEditor.vue'
import AdminPanel from './AdminPanel.vue'
import Profile from './Profile.vue'
import Auth from './Auth.vue'

// Router
const router = useRouter()

// 状态
const images = ref<Image[]>([])
const categories = ref<Category[]>([])
const loading = ref(false)
const uploading = ref(false)
const isLoading = ref(false) // 区分首次加载和刷新加载
const toastRef = ref<{ showToast: (message: string, type?: ToastType) => void } | null>(null)

const pagination = ref<Pagination>({
  page: 1,
  page_size: CONSTANTS.PAGINATION.DEFAULT_PAGE_SIZE,
  total: 0,
  has_next: false
})

const preview = ref({ visible: false, image: null as Image | null })
const uploadZoneRef = ref()

// UI 状态
const showCategoryModal = ref(false)
const showEditor = ref(false)
const editingImage = ref<Image | null>(null)
const showAdminPanel = ref(false)
const showProfile = ref(false)

// 筛选和排序
const searchQuery = ref('')
const sortBy = ref('created_at')
const sortOrder = ref<'ASC' | 'DESC'>('DESC')
const selectedCategory = ref('')

// 刷新触发器
const refreshTrigger = ref(0)

// 计算属性
const user = computed(() => auth.state.user)
const authenticated = computed(() => auth.isAuthenticated())
const theme = ref<'light' | 'dark'>(
  (localStorage.getItem(CONSTANTS.STORAGE_KEYS.THEME) || CONSTANTS.THEME.DEFAULT) as 'light' | 'dark'
)

// 防抖搜索
const debouncedSearch = debounce(() => {
  loadImages(1)
}, CONSTANTS.DEBOUNCE.SEARCH)

// Toast 显示
const showToast = (message: string, type: ToastType = 'success') => {
  toastRef.value?.showToast(message, type)
}

// 认证成功处理
const handleAuthSuccess = (isLogin: boolean) => {
  toastSuccess(isLogin ? '登录成功' : '注册成功')
  loadImages()
  loadCategories()
}

// 退出登录
const handleLogout = () => {
  auth.logout()
  images.value = []
  pagination.value = {
    page: 1,
    page_size: CONSTANTS.PAGINATION.DEFAULT_PAGE_SIZE,
    total: 0,
    has_next: false
  }
  toastSuccess('已退出登录')
}

// 加载分类
const loadCategories = async () => {
  try {
    categories.value = await api.getCategories()
  } catch (error) {
    console.error('加载分类失败:', error)
  }
}

// 加载图片
const loadImages = async (page = 1) => {
  loading.value = true
  isLoading.value = page === 1

  try {
    const data = await api.getImages({
      page,
      page_size: pagination.value.page_size,
      sort_by: sortBy.value,
      sort_order: sortOrder.value,
      search: searchQuery.value || undefined,
      category_id: selectedCategory.value || undefined
    })
    images.value = data.data
    pagination.value = data
    refreshTrigger.value++
  } catch (error) {
    showToast('加载图片失败', 'error')
    console.error('加载图片失败:', error)
  } finally {
    loading.value = false
    isLoading.value = false
  }
}

// 搜索输入处理（防抖）
const handleSearchInput = () => {
  debouncedSearch()
}

// 排序/筛选变化处理
const handleSortChange = () => {
  loadImages(1)
}

// 上传处理
const handleUpload = async (files: FileList) => {
  uploading.value = true
  const fileArray = Array.from(files)

  // 验证文件
  const validation = validateFiles(fileArray)
  if (!validation.valid) {
    uploading.value = false
    showToast(validation.errors[0], 'error')
    return
  }

  let successCount = 0
  let failCount = 0

  for (let i = 0; i < fileArray.length; i++) {
    const file = fileArray[i]
    const current = i + 1
    uploadZoneRef.value?.updateProgress(current, fileArray.length, file.name)

    try {
      const result = await api.uploadImage(file)
      if (result) {
        successCount++
      } else {
        failCount++
      }
    } catch (error) {
      console.error(`上传 ${file.name} 失败:`, error)
      failCount++
    }
  }

  uploading.value = false

  if (successCount > 0) {
    const message = `上传完成: 成功 ${successCount} 张${failCount > 0 ? `, 失败 ${failCount} 张` : ''}`
    showToast(message, 'success')
    await loadImages(1)
  } else {
    showToast('上传失败', 'error')
  }
}

// 文件验证
const validateFiles = (files: File[]) => {
  const errors: string[] = []
  const validFiles: File[] = []

  for (let i = 0; i < files.length; i++) {
    const result = validateImageFile(files[i])
    if (result.valid) {
      validFiles.push(files[i])
    } else {
      errors.push(`${files[i].name}: ${result.error}`)
    }
  }

  if (errors.length > 0) {
    return { valid: false, errors, validFiles }
  }

  if (validFiles.length > CONSTANTS.IMAGE.MAX_UPLOAD_FILES) {
    errors.push(`一次最多只能上传 ${CONSTANTS.IMAGE.MAX_UPLOAD_FILES} 个文件`)
    return { valid: false, errors, validFiles }
  }

  return { valid: true, errors: [], validFiles }
}

// 图片操作处理
const handleUpdate = async (id: string, data: { category_id?: string; tags?: string[] }) => {
  const success = await api.updateImage(id, data)
  if (success) {
    showToast('更新成功', 'success')
    await loadImages(pagination.value.page)
  } else {
    showToast('更新失败', 'error')
  }
}

const handleRename = async (id: string, filename: string) => {
  const result = await showConfirm({
    title: '重命名',
    message: `确定重命名为 "${filename}" 吗？`,
    type: 'default'
  })
  if (result.confirm) {
    const success = await api.renameImage(id, filename)
    if (success) {
      showToast('重命名成功', 'success')
      await loadImages(pagination.value.page)
    } else {
      showToast('重命名失败', 'error')
    }
  }
}

const handleSetExpiry = async (id: string, expiresAt: string | null) => {
  const message = expiresAt
    ? `确定要设置过期时间吗？`
    : '确定要取消过期时间吗？'

  const result = await showConfirm({
    title: '设置过期时间',
    message,
    type: 'default'
  })

  if (result.confirm) {
    const success = await api.setExpiry(id, expiresAt)
    if (success) {
      showToast(expiresAt ? '已设置过期时间' : '已取消过期时间', 'success')
      await loadImages(pagination.value.page)
    } else {
      showToast('设置失败', 'error')
    }
  }
}

const handleDelete = async (ids: string[]) => {
  const result = await showConfirm({
    title: '删除图片',
    message: `确定要删除这 ${ids.length} 张图片吗？`,
    details: '删除后图片将移至回收站',
    type: 'danger'
  })

  if (result.confirm) {
    const success = await api.deleteImages(ids, false)
    if (success) {
      showToast(`已将 ${ids.length} 张图片移至回收站`, 'success')
      await loadImages(pagination.value.page)
    } else {
      showToast('删除失败', 'error')
    }
  }
}

const handleDuplicate = async (id: string) => {
  const result = await api.duplicateImage(id)
  if (result) {
    showToast('图片复制成功', 'success')
    await loadImages(pagination.value.page)
  } else {
    showToast('图片复制失败', 'error')
  }
}

const handlePreview = (image: Image) => {
  preview.value = { visible: true, image }
}

const handleEdit = (image: Image) => {
  editingImage.value = image
  showEditor.value = true
}

const handleEditApplied = async (image: Image) => {
  showToast('图片编辑成功', 'success')
  await loadImages(pagination.value.page)
}

const handleTrashRefresh = () => {
  refreshTrigger.value++
}

const handleCategoryCreated = () => {
  loadCategories()
}

// 主题切换
const toggleTheme = () => {
  theme.value = theme.value === 'light' ? 'dark' : 'light'
  localStorage.setItem(CONSTANTS.STORAGE_KEYS.THEME, theme.value)
}

// 监听主题变化（来自 App.vue）
watch(() => theme.value, (newTheme) => {
  document.documentElement.setAttribute('data-theme', newTheme)
})

// 初始化
onMounted(() => {
  // 设置初始主题
  document.documentElement.setAttribute('data-theme', theme.value)

  // 设置全局 Toast
  if (toastRef.value) {
    setGlobalToast(toastRef.value)
  }

  // 初始化认证
  auth.init()

  // 如果已登录，加载数据
  if (auth.state.token) {
    loadImages()
    loadCategories()
  }
})
</script>

<style scoped>
.home {
  max-width: 1440px;
  margin: 0 auto;
  padding: 24px;
  min-height: 100vh;
}

/* 头部 */
header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 32px;
  padding: 24px;
  background: var(--glass-bg);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-xl);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
}

h1 {
  margin: 0;
  font-size: 2rem;
  font-weight: var(--font-weight-bold);
  background: var(--gradient-primary);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.subtitle {
  color: var(--text-secondary);
  font-size: var(--font-size-sm);
  margin-top: 6px;
}

.header-actions {
  display: flex;
  gap: 10px;
  align-items: center;
}

.user-info {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 8px 16px;
  background: var(--bg-tertiary);
  border-radius: var(--radius-full);
}

.user-info span {
  font-size: var(--font-size-sm);
  color: var(--text-primary);
  font-weight: var(--font-weight-semibold);
}

/* 按钮样式 */
.btn-profile,
.btn-admin,
.btn-settings,
.btn-logout,
.btn-theme {
  padding: 10px 18px;
  border: 1px solid var(--border-color);
  border-radius: var(--radius-lg);
  background: var(--bg-secondary);
  color: var(--text-primary);
  cursor: pointer;
  font-size: var(--font-size-sm);
  font-weight: var(--font-weight-medium);
  transition: all var(--transition-normal) var(--ease-out);
  display: flex;
  align-items: center;
  gap: 6px;
}

.btn-profile:hover,
.btn-admin:hover,
.btn-settings:hover,
.btn-logout:hover,
.btn-theme:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  border-color: var(--color-primary);
}

.btn-admin {
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(168, 85, 247, 0.1) 100%);
  color: var(--color-primary);
}

.btn-logout:hover {
  border-color: var(--color-danger);
  color: var(--color-danger);
}

.btn-theme {
  font-size: 1.25rem;
  background: var(--bg-tertiary);
}

/* 工具栏 */
.toolbar {
  display: flex;
  gap: 12px;
  align-items: center;
  padding: 20px 24px;
  background: var(--glass-bg);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-xl);
  margin-bottom: 24px;
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
}

.search-box {
  display: flex;
  gap: 10px;
  flex: 1;
  flex-wrap: wrap;
}

.search-box input {
  flex: 1;
  min-width: 240px;
  padding: 12px 18px;
  border: 2px solid var(--border-color);
  border-radius: var(--radius-lg);
  background: var(--bg-primary);
  font-size: var(--font-size-sm);
  color: var(--text-primary);
  transition: all var(--transition-normal) var(--ease-out);
  font-weight: var(--font-weight-medium);
}

.search-box input::placeholder {
  color: var(--text-tertiary);
}

.search-box input:focus {
  outline: none;
  border-color: var(--color-primary);
  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.1);
}

.search-box input:disabled {
  opacity: 0.6;
  cursor: not-allowed;
  background: var(--bg-tertiary);
}

.sort-select,
.sort-order,
.category-select {
  padding: 12px 18px;
  border: 2px solid var(--border-color);
  border-radius: var(--radius-lg);
  background: var(--bg-primary);
  cursor: pointer;
  font-size: var(--font-size-sm);
  color: var(--text-primary);
  font-weight: var(--font-weight-medium);
  transition: all var(--transition-normal) var(--ease-out);
}

.sort-select:hover,
.sort-order:hover,
.category-select:hover {
  border-color: var(--color-primary);
}

.sort-select:focus,
.sort-order:focus,
.category-select:focus {
  outline: none;
  border-color: var(--color-primary);
  box-shadow: 0 0 0 4px rgba(102, 126, 234, 0.1);
}

/* 上传区域 */
.upload-section {
  margin-bottom: 24px;
}

/* 未认证状态 */
.unauth {
  display: flex;
  justify-content: center;
  align-items: center;
  min-height: 60vh;
}

/* 响应式 */
@media (max-width: 768px) {
  .home {
    padding: 16px;
  }

  header {
    flex-direction: column;
    align-items: flex-start;
    gap: 20px;
    padding: 20px;
  }

  h1 {
    font-size: 1.5rem;
  }

  .header-actions {
    width: 100%;
    justify-content: space-between;
    flex-wrap: wrap;
  }

  .search-box {
    flex-direction: column;
  }

  .search-box input {
    width: 100%;
    min-width: unset;
  }

  .toolbar {
    padding: 16px;
    flex-direction: column;
    align-items: stretch;
  }

  .sort-select,
  .sort-order,
  .category-select {
    width: 100%;
  }
}

/* 减少动画 */
@media (prefers-reduced-motion: reduce) {
  .btn-profile:hover,
  .btn-admin:hover,
  .btn-settings:hover,
  .btn-logout:hover,
  .btn-theme:hover {
    transform: none;
  }
}
</style>

// frontend/src/components/Home.svelte
<script lang="ts">
  import { imagesState, loadImagesCursor, toggleSelect, clearSelection } from '../stores/images'
  import { isAuthenticated, currentUser } from '../stores/auth'
  import { toastSuccess, toastError } from '../stores/toast'
  import { formatFileSize } from '../utils/format'
  import { debounce } from '../utils/debounce'
  import type { Image } from '../types'
  import ImageCard from './ImageCard.svelte'
  import ImagePreview from './ImagePreview.svelte'
  import UploadZone from './UploadZone.svelte'
  import UserMenu from './UserMenu.svelte'

  let searchQuery = ''
  let sortBy = 'created_at'
  let sortOrder: 'ASC' | 'DESC' = 'DESC'

  const debouncedSearch = debounce(() => {
    loadImagesCursor({
      page_size: 20,
      sort_by: sortBy,
      sort_order: sortOrder,
      search: searchQuery || undefined,
    })
  }, 300)

  function handleSearchInput() {
    debouncedSearch()
  }

  function handleSortChange() {
    loadImagesCursor({
      page_size: 20,
      sort_by: sortBy,
      sort_order: sortOrder,
      search: searchQuery || undefined,
    })
  }

  function handleSelect(id: string) {
    toggleSelect(id)
  }

  function handlePreview(image: Image) {
    // 打开预览
  }

  async function handleDelete(ids: string[]) {
    // 使用对话框确认删除
  }

  function handleDuplicate(id: string) {
    // 复制图片
  }

  function handleLogout() {
    clearSelection()
  }
</script>

<div class="home">
  <!-- 头部 -->
  <header>
    <div class="header-left">
      <h1>VanSour Image</h1>
      <p class="subtitle">简单快速的图片托管服务</p>
    </div>
    <div class="header-right">
      {#if $isAuthenticated && $currentUser}
        <UserMenu
          user={$currentUser}
          on:logout={handleLogout}
        />
      {/if}
    </div>
  </header>

  <!-- 工具栏 -->
  <div class="toolbar">
    <div class="search-box">
      <input
        type="text"
        placeholder="搜索图片名称..."
        bind:value={searchQuery}
        on:input={handleSearchInput}
        disabled={$imagesState.loading}
      />
      <select bind:value={sortBy} on:change={handleSortChange} disabled={$imagesState.loading}>
        <option value="created_at">上传时间</option>
        <option value="views">浏览量</option>
        <option value="size">大小</option>
      </select>
      <select bind:value={sortOrder} on:change={handleSortChange} disabled={$imagesState.loading}>
        <option value="DESC">降序</option>
        <option value="ASC">升序</option>
      </select>
    </div>
  </div>

  <!-- 上传区域 -->
  <div class="upload-section">
    <UploadZone />
  </div>

  <!-- 批量操作栏 -->
  {#if $imagesState.selectedIds.size > 0}
    <div class="bulk-actions">
      <span class="selection-info">已选择 {$imagesState.selectedIds.size} 张</span>
      <button class="btn" on:click={clearSelection}>取消</button>
      <button class="btn btn-danger" on:click={() => handleDelete([...$imagesState.selectedIds])}>删除</button>
    </div>
  {/if}

  <!-- 骨架屏 -->
  {#if $imagesState.loading}
    <div class="skeleton-grid">
      {#each Array(12) as _}
        <div class="skeleton-item">
          <div class="skeleton-image"></div>
          <div class="skeleton-info">
            <div class="skeleton-line"></div>
            <div class="skeleton-line short"></div>
          </div>
        </div>
      {/each}
    </div>
  {:else}
    <!-- 图片列表 -->
    <div class="image-grid">
      {#each $imagesState.images as image (image.id)}
        <ImageCard
          {image}
          selected={$imagesState.selectedIds.has(image.id)}
          on:select={() => handleSelect(image.id)}
          on:preview={handlePreview}
          on:delete={() => handleDelete([image.id])}
          on:duplicate={() => handleDuplicate(image.id)}
        />
      {/each}
    </div>
  {/if}

  {#if $imagesState.images.length === 0 && !$imagesState.loading}
    <div class="empty-state">
      <div class="empty-icon">Image</div>
      <p>暂无图片</p>
      <p>拖拽图片到这里或点击上传</p>
    </div>
  {/if}
</div>

<style>
  .home {
    max-width: 1440px;
    margin: 0 auto;
    padding: 1.5rem;
    min-height: 100vh;
  }

  header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1.5rem;
    background: var(--glass-bg);
    border: 1px solid var(--glass-border);
    border-radius: var(--radius-xl);
    backdrop-filter: blur(var(--glass-blur));
    margin-bottom: 1.5rem;
  }

  .header-left h1 {
    margin: 0;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    background-clip: text;
    font-size: 1.75rem;
    font-weight: var(--font-weight-bold);
  }

  .subtitle {
    color: var(--muted-foreground);
    margin: 0.25rem 0 0 0;
    font-size: var(--font-size-sm);
  }

  .toolbar {
    display: flex;
    gap: 0.75rem;
    padding: 1rem 1.5rem;
    background: var(--glass-bg);
    border: 1px solid var(--glass-border);
    border-radius: var(--radius-xl);
    margin-bottom: 1.5rem;
    backdrop-filter: blur(var(--glass-blur));
  }

  .search-box {
    display: flex;
    gap: 0.75rem;
    flex: 1;
    flex-wrap: wrap;
  }

  .search-box input,
  .search-box select {
    padding: 0.75rem 1rem;
    border: 2px solid var(--border);
    border-radius: var(--radius-lg);
    font-size: var(--font-size-sm);
    background: var(--background);
    color: var(--foreground);
  }

  .search-box input:focus,
  .search-box select:focus {
    outline: none;
    border-color: var(--primary);
    box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.1);
  }

  .upload-section {
    margin-bottom: 1.5rem;
  }

  .bulk-actions {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 1rem 1.5rem;
    background: rgba(255, 107, 107, 0.1);
    border-radius: var(--radius-lg);
    margin-bottom: 1rem;
  }

  .selection-info {
    font-weight: var(--font-weight-medium);
  }

  .btn {
    padding: 0.5rem 1rem;
    border: none;
    border-radius: var(--radius-lg);
    cursor: pointer;
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-medium);
    transition: all var(--transition-fast);
  }

  .btn-danger {
    background: var(--destructive);
    color: var(--destructive-foreground);
  }

  .image-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 1rem;
  }

  .skeleton-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 1rem;
  }

  .skeleton-item {
    position: relative;
  }

  .skeleton-image {
    aspect-ratio: 1;
    background: var(--muted);
    border-radius: var(--radius-lg);
    overflow: hidden;
    position: relative;
  }

  .skeleton-image::after {
    content: '';
    position: absolute;
    inset: 0;
    background: linear-gradient(
      90deg,
      transparent 0%,
      rgba(255, 255, 255, 0.5) 50%,
      rgba(0, 0, 0, 0) 50%
    );
    background-size: 200% 100%;
    animation: shimmer 1.5s infinite;
  }

  .skeleton-info {
    padding: 0.75rem;
  }

  .skeleton-line {
    height: 20px;
    background: var(--muted);
    border-radius: var(--radius-md);
  }

  .skeleton-line.short {
    height: 14px;
    width: 60%;
  }

  @keyframes shimmer {
    0% {
      background-position: -200% 0;
    }
    100% {
      background-position: 200% 0;
    }
  }

  .empty-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 4rem 2rem;
    text-align: center;
  }

  .empty-icon {
    font-size: 4rem;
    margin-bottom: 1rem;
    opacity: 0.3;
  }

  @media (max-width: 768px) {
    .home {
      padding: 1rem;
    }

    header {
      flex-direction: column;
      gap: 1rem;
      align-items: flex-start;
    }

    .search-box {
      flex-direction: column;
    }

    .search-box input,
    .search-box select {
      width: 100%;
    }
}
</style>
