// frontend/src/components/LocaleSwitcher.svelte
<script lang="ts">
  import { writable } from 'svelte/store'
  import { Globe } from 'lucide-svelte'
  import { locale, loadLocaleAsync } from 'svelte-i18n'

  export let className: string = ''

  const availableLocales = [
    { code: 'zh', name: '简体中文' },
    { code: 'en', name: 'English' }
  ]

  let isOpen = writable<boolean>(false)

  const currentLocaleName = () => {
    const found = availableLocales.find(l => l.code === $locale)
    return found ? found.name : $locale
  }

  const switchLocale = async (newLocale: string) => {
    if (newLocale === $locale) return
    await loadLocaleAsync(newLocale)
    locale.set(newLocale)
    isOpen.set(false)

    // 保存到 localStorage
    localStorage.setItem('locale', newLocale)
  }

  const toggleMenu = () => {
    isOpen.set(!$isOpen)
  }

  const closeMenu = () => {
    isOpen.set(false)
  }
</script>

<div class="locale-switcher {className}">
  <button
    class="locale-button"
    class:open={$isOpen}
    on:click={toggleMenu}
    aria-label="切换语言"
    aria-expanded={$isOpen}
  >
    <Globe size={16} />
    <span class="locale-name">{currentLocaleName()}</span>
  </button>

  {#if $isOpen}
    <div class="locale-menu">
      <div class="locale-menu-backdrop" on:click={closeMenu}></div>
      <div class="locale-menu-content">
        {#each availableLocales as loc (loc.code)}
          <button
            class="locale-option"
            class:active={loc.code === $locale}
            on:click={() => switchLocale(loc.code)}
          >
            <span class="locale-option-name">{loc.name}</span>
            {#if loc.code === $locale}
              <span class="locale-option-check">✓</span>
            {/if}
          </button>
        {/each}
      </div>
    </div>
  {/if}
</div>

<style>
.locale-switcher {
  position: relative;
  display: inline-block;
}

.locale-button {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 12px;
  background: var(--bg-secondary);
  border: 1px solid var(--border-color);
  border-radius: var(--radius-md);
  color: var(--text-primary);
  font-size: var(--font-size-sm);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.locale-button:hover {
  background: var(--bg-tertiary);
  border-color: var(--color-primary);
}

.locale-button.open {
  background: var(--color-primary);
  color: white;
  border-color: var(--color-primary);
}

.locale-button :global(svg) {
  width: 16px;
  height: 16px;
}

.locale-name {
  font-weight: var(--font-weight-medium);
}

.locale-menu {
  position: absolute;
  top: calc(100% + 8px);
  right: 0;
  z-index: 100;
  animation: menuFadeIn 0.2s ease-out;
}

@keyframes menuFadeIn {
  from {
    opacity: 0;
    transform: translateY(-8px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.locale-menu-backdrop {
  position: fixed;
  inset: 0;
  z-index: -1;
}

.locale-menu-content {
  background: var(--bg-primary);
  border: 1px solid var(--border-color);
  border-radius: var(--radius-lg);
  box-shadow: var(--shadow-xl);
  overflow: hidden;
  min-width: 140px;
}

.locale-option {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  padding: 10px 16px;
  background: transparent;
  border: none;
  color: var(--text-primary);
  font-size: var(--font-size-sm);
  cursor: pointer;
  transition: all var(--transition-fast);
}

.locale-option:hover {
  background: var(--bg-secondary);
}

.locale-option.active {
  background: rgba(102, 126, 234, 0.1);
  color: var(--color-primary);
  font-weight: var(--font-weight-medium);
}

.locale-option-name {
  text-align: left;
}

.locale-option-check {
  color: var(--color-primary);
  font-weight: bold;
}

@media (max-width: 480px) {
  .locale-menu {
    right: auto;
    left: 0;
  }

  .locale-menu-content {
    min-width: 120px;
  }
}
</style>

// frontend/src/components/LocaleSwitcher.vue
<template>
  <div class="locale-switcher">
    <button
      class="locale-btn"
      :class="{ active: currentLocale === 'zh-CN' }"
      @click="setLocale('zh-CN')"
      :aria-label="'切换中文'"
    >
      中
    </button>
    <span class="locale-divider">|</span>
    <button
      class="locale-btn"
      :class="{ active: currentLocale === 'en-US' }"
      @click="setLocale('en-US')"
      :aria-label="'Switch to English'"
    >
      EN
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'

const { locale } = useI18n<[typeof import('@/locales').MessageSchema]>()

const currentLocale = computed(() => locale.value)

function setLocale(lang: 'zh-CN' | 'en-US') {
  locale.value = lang
  localStorage.setItem('locale', lang)
}
</script>

<style scoped>
.locale-switcher {
  display: flex;
  align-items: center;
  gap: 4px;
  padding: 4px;
  background: var(--bg-secondary, #fff);
  border: 1px solid var(--border-color, #ddd);
  border-radius: 4px;
}

.locale-btn {
  padding: 4px 12px;
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 12px;
  color: var(--text-secondary, #666);
  border-radius: 2px;
  transition: all 0.2s;
}

.locale-btn:hover {
  background: var(--hover-bg, #f0f0f0);
}

.locale-btn.active {
  background: var(--theme-color, #007bff);
  color: white;
}

.locale-divider {
  color: var(--border-color, #ddd);
  user-select: none;
}
</style>
