// frontend/src/components/UploadZone.vue
<template>
  <div class="upload-zone" :class="{ dragover, uploading }" @dragover.prevent="dragover = true" @dragleave="dragover = false" @drop.prevent="handleDrop" @click="!uploading && triggerUpload()">
    <input ref="fileInput" type="file" accept="image/*" multiple style="display: none" @change="handleSelect" />
    <div v-if="!uploading" class="upload-content">
      <div class="upload-icon">
        <Upload :size="36" />
      </div>
      <h3>拖拽图片到这里</h3>
      <p class="subtitle">或者点击选择文件（支持多选）</p>
      <div class="file-types">
        <span>JPG</span>
        <span>PNG</span>
        <span>WEBP</span>
        <span>GIF</span>
      </div>
    </div>
    <div v-else class="upload-progress">
      <div class="progress-ring">
        <span class="progress-percentage">{{ Math.round(progressPercentage) }}%</span>
      </div>
      <div class="progress-info">
        <span class="filename">{{ currentFileName || '上传中...' }}</span>
        <span class="count">{{ uploadedCount }} / {{ totalCount }}</span>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { Upload } from 'lucide-vue-next'

const props = defineProps<{
  uploading: boolean
}>()

const emit = defineEmits<{
  upload: [files: FileList]
}>()

const dragover = ref(false)
const draggingFiles = ref<File[]>([])
const fileInput = ref<HTMLInputElement>()
const uploadedCount = ref(0)
const totalCount = ref(0)
const currentFileName = ref('')
const currentProgress = ref(0)

const progressCircumference = 2 * Math.PI * 45 // 2πr

const progressPercentage = computed(() => {
  if (totalCount.value === 0) return 0
  return ((uploadedCount.value + currentProgress.value / 100) / totalCount.value) * 100
})

const progressOffset = computed(() => {
  return progressCircumference - (progressPercentage.value / 100) * progressCircumference
})

const handleDrop = (e: DragEvent) => {
  dragover.value = false
  const files = e.dataTransfer?.files
  if (files && files.length > 0) {
    const imageFiles = Array.from(files).filter(f => f.type.startsWith('image/'))
    if (imageFiles.length > 0) {
      emitUploadFiles(imageFiles)
    }
  }
}

const handleSelect = (e: Event) => {
  const files = (e.target as HTMLInputElement).files
  if (files && files.length > 0) {
    emitUploadFiles(Array.from(files))
  }
}

const emitUploadFiles = (files: File[]) => {
  draggingFiles.value = files
  setTimeout(() => {
    draggingFiles.value = []
  }, 100)
  emit('upload', files as any)
}

const updateProgress = (current: number, total: number, filename: string, fileProgress: number = 0) => {
  uploadedCount.value = current
  totalCount.value = total
  currentProgress.value = fileProgress
  currentFileName.value = filename.length > 30 ? filename.slice(0, 30) + '...' : filename
}

const triggerUpload = () => fileInput.value?.click()

defineExpose({ updateProgress })
</script>

<style scoped>
.upload-zone {
  border: 3px dashed var(--border-color);
  border-radius: var(--radius-xl);
  padding: 48px 32px;
  text-align: center;
  cursor: pointer;
  transition: all var(--transition-normal) var(--ease-out);
  background: var(--bg-secondary);
  position: relative;
  overflow: hidden;
}

.upload-zone::before {
  content: '';
  position: absolute;
  top: -50%;
  left: -50%;
  width: 200%;
  height: 200%;
  background: radial-gradient(circle, rgba(102, 126, 234, 0.03) 0%, transparent 70%);
  opacity: 0;
  transition: opacity var(--transition-normal) var(--ease-out);
  pointer-events: none;
}

.upload-zone:hover,
.upload-zone.dragover {
  border-color: var(--color-primary);
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.05) 0%, rgba(118, 75, 162, 0.05) 100%);
}

.upload-zone:hover::before,
.upload-zone.dragover::before {
  opacity: 1;
}

.upload-zone.dragover {
  transform: scale(1.02);
  box-shadow: var(--shadow-glow-primary);
}

.upload-zone.uploading {
  pointer-events: none;
  opacity: 0.9;
  border-style: solid;
}

/* 上传内容 */
.upload-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
}

.upload-icon {
  width: 72px;
  height: 72px;
  border-radius: var(--radius-xl);
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.1) 0%, rgba(168, 85, 247, 0.1) 100%);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all var(--transition-normal) var(--ease-out);
  color: var(--color-primary);
}

.upload-icon svg {
  width: 36px;
  height: 36px;
  transition: transform var(--transition-normal) var(--ease-out);
}

.upload-zone:hover .upload-icon {
  transform: translateY(-4px);
}

.upload-zone:hover .upload-icon svg {
  transform: scale(1.1);
}

.upload-content h3 {
  margin: 0;
  color: var(--text-primary);
  font-size: 1.2rem;
  font-weight: var(--font-weight-semibold);
}

.subtitle {
  margin: 0;
  color: var(--text-secondary);
  font-size: var(--font-size-sm);
}

.file-types {
  display: flex;
  gap: 8px;
  margin-top: 8px;
}

.file-types span {
  padding: 6px 12px;
  background: var(--bg-tertiary);
  border-radius: var(--radius-md);
  font-size: var(--font-size-xs);
  font-weight: var(--font-weight-medium);
  color: var(--text-secondary);
  border: 1px solid var(--border-color);
}

/* 进度 */
.upload-progress {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
}

.progress-ring {
  position: relative;
  width: 100px;
  height: 100px;
}

.progress-svg {
  width: 100%;
  height: 100%;
  transform: rotate(-90deg);
}

.progress-bg {
  fill: none;
  stroke: var(--border-color);
  stroke-width: 8;
}

.progress-bar {
  fill: none;
  stroke: var(--color-primary);
  stroke-width: 8;
  stroke-linecap: round;
  transition: stroke-dashoffset 0.3s ease-out;
}

.progress-percentage {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 1.2rem;
  font-weight: var(--font-weight-bold);
  color: var(--text-primary);
}

.progress-info {
  display: flex;
  flex-direction: column;
  gap: 6px;
  align-items: center;
}

.filename {
  font-size: var(--font-size-base);
  color: var(--text-primary);
  font-weight: var(--font-weight-medium);
}

.count {
  font-size: var(--font-size-sm);
  color: var(--text-secondary);
  padding: 4px 12px;
  background: var(--bg-tertiary);
  border-radius: var(--radius-full);
}

/* 响应式 */
@media (max-width: 480px) {
  .upload-zone {
    padding: 36px 20px;
  }

  .upload-icon {
    width: 56px;
    height: 56px;
  }

  .upload-icon span {
    font-size: 28px;
  }

  .upload-content h3 {
    font-size: 1.1rem;
  }

  .file-types {
    flex-wrap: wrap;
    justify-content: center;
  }
}

/* 减少动画模式 */
@media (prefers-reduced-motion: reduce) {
  .upload-zone:hover .upload-icon,
  .upload-zone:hover .upload-icon span {
    transform: none;
  }

  .upload-zone.dragover {
    transform: none;
  }
}
</style>

// frontend/src/components/UploadZone.svelte
<script lang="ts">
  import { uploadImage } from '../stores/api'
  import { toastSuccess, toastError } from '../stores/toast'
  import { UploadCloud } from 'lucide-svelte'

  let isDragging = false
  let uploadProgress = 0
  let uploading = false

  let fileInput: HTMLInputElement

  function handleDragOver(event: DragEvent) {
    event.preventDefault()
    isDragging = true
  }

  function handleDragLeave(event: DragEvent) {
    event.preventDefault()
    isDragging = false
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault()
    isDragging = false

    const files = event.dataTransfer?.files
    if (!files || files.length === 0) return

    handleFiles(files)
  }

  function handleClick() {
    fileInput?.click()
  }

  function handleFileSelect(event: Event) {
    const files = (event.target as HTMLInputElement).files
    if (!files || files.length === 0) return

    handleFiles(files)
  }

  async function handleFiles(files: FileList) {
    const fileArray = Array.from(files)
    uploading = true
    uploadProgress = 0
    let successCount = 0

    try {
      for (let i = 0; i < fileArray.length; i++) {
        const file = fileArray[i]

        try {
          const result = await uploadImage(file)
          if (result) {
            successCount++
          }
        } catch (error) {
          console.error('上传失败:', error)
        }

        uploadProgress = Math.round(((i + 1) / fileArray.length) * 100)
      }

      if (successCount > 0) {
        toastSuccess(`上传完成: 成功 ${successCount} 张${fileArray.length - successCount > 0 ? `, 失败 ${fileArray.length - successCount} 张` : ''}`)
      } else {
        toastError('上传失败')
      }
    } finally {
      uploading = false
      uploadProgress = 0
    }
  }
</script>

  <div
    class="upload-zone {isDragging ? 'dragging' : ''}"
    role="button"
    aria-label="上传图片区域，拖拽图片到这里或点击选择图片"
    aria-dropeffect="copy"
    tabindex="0"
    on:dragover={handleDragOver}
    on:dragleave={handleDragLeave}
    on:drop={handleDrop}
    on:keydown={(e) => e.key === 'Enter' || e.key === ' ' ? handleClick() : null}
  >
  <input
  type="file"
  accept="image/*"
  multiple
  bind:this={fileInput}
  on:change={handleFileSelect}
  class="hidden-input"
/>

  <div class="upload-content">
    {#if uploading}
      <div class="uploading-state">
        <div class="progress-ring">
          <svg class="progress-circle" viewBox="0 0 36 36">
            <circle
              class="progress-bg"
              cx="18"
              cy="18"
              r="15.9"
              fill="none"
            />
            <circle
              class="progress-fill"
              cx="18"
              cy="18"
              r="15.9"
              fill="none"
              stroke="var(--primary)"
              stroke-dasharray={`${2 * Math.PI * 15.9} ${2 * Math.PI * 15.9}`}
              stroke-dashoffset={`${2 * Math.PI * 15.9 * (1 - uploadProgress / 100)}`}
              stroke-linecap="round"
            />
          </svg>
          <span class="progress-text">{uploadProgress}%</span>
        </div>
      </div>
    {:else}
   <div class="upload-prompt">
        <UploadCloud size={48} />
        <p>{isDragging ? '释放以上传图片' : '拖拽图片到这里或点击上传'}</p>
        <button class="btn-upload" on:click={handleClick} aria-label="选择图片">
          选择图片
        </button>
      </div>
    {/if}
  </div>
</div>

<style>
  .upload-zone {
    position: relative;
    border: 2px dashed var(--border);
    border-radius: var(--radius-xl);
    background: var(--card);
    transition: all var(--transition-normal);
  }

  .upload-zone.dragging {
    border-color: var(--primary);
    background: rgba(102, 126, 234, 0.05);
  }

  .hidden-input {
    display: none;
  }

  .upload-content {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    min-height: 200px;
    gap: 1rem;
  }

  .upload-prompt {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .upload-prompt p {
    color: var(--muted-foreground);
    font-size: var(--font-size-sm);
  }

  .btn-upload {
    padding: 0.75rem 2rem;
    background: var(--primary);
    color: var(--primary-foreground);
    border: none;
    border-radius: var(--radius-lg);
    font-size: var(--font-size-base);
    font-weight: var(--font-weight-medium);
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .btn-upload:hover {
    background: var(--primary-foreground);
    color: var(--primary);
  }

  .uploading-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .progress-ring {
    position: relative;
    width: 80px;
    height: 80px;
  }

  .progress-circle {
    transform: rotate(-90deg);
  }

  .progress-bg {
    stroke: var(--muted);
    stroke-width: 3;
  }

  .progress-fill {
    stroke-width: 3;
    transition: stroke-dashoffset 0.3s ease-out;
  }

  .progress-text {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: var(--font-size-sm);
    font-weight: var(--font-weight-medium);
  }
</style>
