// frontend/src/components/UserMenu.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { logout, currentUser } from '../stores/auth'
  import { navigate } from '../stores/router'
  import { themeMode, toggleTheme, getThemeLabel, initTheme, setTheme } from '../stores/theme'
  import { LogOut, User, ChevronDown, Moon, Sun, Monitor, Settings } from 'lucide-svelte'

  export let onSettings: () => void = () => {}

  let showMenu = false
  let menuEl: HTMLElement
  let triggerEl: HTMLButtonElement
  let focusedIndex = 0

  function toggleMenu(event: MouseEvent) {
    event.stopPropagation()
    showMenu = !showMenu
    if (showMenu) {
      focusedIndex = 0
      setTimeout(() => {
        const items = menuEl?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]')
        items?.[0]?.focus()
      }, 50)
    }
  }

  function closeMenu() {
    showMenu = false
    triggerEl?.focus()
  }

  function handleLogout() {
    logout()
    closeMenu()
  }

  function handleSettings() {
    onSettings()
    closeMenu()
  }

  function handleProfile() {
    navigate('/profile')
    closeMenu()
  }

  function handleThemeToggle() {
    toggleTheme()
  }

  // 菜单键盘导航
  function handleMenuKeyDown(event: KeyboardEvent) {
    if (!showMenu) return

    const items = menuEl?.querySelectorAll<HTMLButtonElement>('[role="menuitem"]') || []
    const itemCount = items.length

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault()
        focusedIndex = (focusedIndex + 1) % itemCount
        items[focusedIndex]?.focus()
        break
      case 'ArrowUp':
        event.preventDefault()
        focusedIndex = (focusedIndex - 1 + itemCount) % itemCount
        items[focusedIndex]?.focus()
        break
      case 'Escape':
        event.preventDefault()
        closeMenu()
        break
      case 'Home':
        event.preventDefault()
        focusedIndex = 0
        items[0]?.focus()
        break
      case 'End':
        event.preventDefault()
        focusedIndex = itemCount - 1
        items[itemCount - 1]?.focus()
        break
    }
  }

  // 点击外部关闭菜单
  onMount(() => {
    initTheme()

    const handleClickOutside = (event: MouseEvent) => {
      if (menuEl && !menuEl.contains(event.target as Node)) {
        showMenu = false
      }
    }
    document.addEventListener('click', handleClickOutside)
    return () => document.removeEventListener('click', handleClickOutside)
  })
</script>

<div class="user-menu">
  <button
    class="menu-trigger"
    bind:this={triggerEl}
    on:click={toggleMenu}
    on:keydown={(e) => {
      if (e.key === 'ArrowDown' || e.key === 'Enter' || e.key === ' ') {
        e.preventDefault()
        if (!showMenu) toggleMenu(e as unknown as MouseEvent)
      }
    }}
    aria-label="用户菜单"
    aria-expanded={showMenu}
    aria-haspopup="true"
  >
    <div class="user-avatar">
      <User size={20} />
    </div>
    <span class="username">{$currentUser?.username || 'User'}</span>
    <span class="chevron-wrapper" class:rotated={showMenu}>
      <ChevronDown size={16} />
    </span>
  </button>

  {#if showMenu}
    <div class="menu" bind:this={menuEl} on:keydown={handleMenuKeyDown} role="menu" tabindex="-1">
      <!-- 用户信息 -->
      <div class="menu-header">
        <div class="user-info">
          <span class="user-name">{$currentUser?.username}</span>
          <span class="user-role">{$currentUser?.role === 'admin' ? '管理员' : '用户'}</span>
        </div>
      </div>

      <div class="menu-divider"></div>

      <!-- 主题切换 -->
      <div class="theme-section">
        <span class="theme-label">主题</span>
        <div class="theme-options">
          <button
            class="theme-btn"
            class:active={$themeMode === 'dark'}
            on:click={() => setTheme('dark')}
            title="深色模式"
            aria-label="深色模式"
          >
            <Moon size={16} />
          </button>
          <button
            class="theme-btn"
            class:active={$themeMode === 'light'}
            on:click={() => setTheme('light')}
            title="浅色模式"
            aria-label="浅色模式"
          >
            <Sun size={16} />
          </button>
          <button
            class="theme-btn"
            class:active={$themeMode === 'system'}
            on:click={() => setTheme('system')}
            title="跟随系统"
            aria-label="跟随系统"
          >
            <Monitor size={16} />
          </button>
        </div>
      </div>

      <div class="menu-divider"></div>

      <!-- 菜单项 -->
      <button class="menu-item" on:click={handleProfile} role="menuitem" tabindex="-1">
        <User size={16} />
        <span>个人资料</span>
      </button>
      <button class="menu-item" on:click={handleSettings} role="menuitem" tabindex="-1">
        <Settings size={16} />
        <span>设置</span>
      </button>

      <div class="menu-divider"></div>

      <button class="menu-item logout" on:click={handleLogout} role="menuitem" tabindex="-1">
        <LogOut size={16} />
        <span>退出登录</span>
      </button>
    </div>
  {/if}
</div>

<style>
  .user-menu {
    position: relative;
  }

  .menu-trigger {
    display: flex;
    align-items: center;
    gap: 0.625rem;
    padding: 0.5rem 0.75rem;
    border: 1px solid var(--border);
    border-radius: var(--radius-full);
    background: var(--card);
    color: var(--foreground);
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .menu-trigger:hover {
    background: var(--muted);
    border-color: var(--border-light);
  }

  .user-avatar {
    width: 32px;
    height: 32px;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--gradient-primary);
    border-radius: var(--radius-full);
    color: white;
  }

  .username {
    font-weight: var(--font-weight-medium);
    font-size: var(--font-size-sm);
    max-width: 120px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }

  .chevron-wrapper {
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform var(--transition-fast);
    color: var(--muted-foreground);
  }

  .chevron-wrapper.rotated {
    transform: rotate(180deg);
  }

  .menu {
    position: absolute;
    top: calc(100% + 0.5rem);
    right: 0;
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: var(--radius-xl);
    box-shadow: var(--shadow-lg);
    z-index: var(--z-dropdown);
    min-width: 200px;
    padding: 0.5rem;
    animation: menuIn 0.2s ease-out;
  }

  .menu-header {
    padding: 0.75rem;
  }

  .user-info {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .user-name {
    font-weight: var(--font-weight-semibold);
    color: var(--foreground);
  }

  .user-role {
    font-size: var(--font-size-xs);
    color: var(--muted-foreground);
    text-transform: capitalize;
  }

  .menu-divider {
    height: 1px;
    background: var(--border);
    margin: 0.375rem 0;
  }

  .theme-section {
    padding: 0.625rem 0.75rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .theme-label {
    font-size: var(--font-size-sm);
    color: var(--muted-foreground);
  }

  .theme-options {
    display: flex;
    gap: 0.25rem;
  }

  .theme-btn {
    width: 32px;
    height: 32px;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid var(--border);
    border-radius: var(--radius-md);
    background: transparent;
    color: var(--muted-foreground);
    cursor: pointer;
    transition: all var(--transition-fast);
  }

  .theme-btn:hover {
    background: var(--muted);
    color: var(--foreground);
  }

  .theme-btn.active {
    background: var(--primary);
    border-color: var(--primary);
    color: var(--primary-foreground);
  }

  .menu-item {
    width: 100%;
    display: flex;
    align-items: center;
    gap: 0.75rem;
    padding: 0.625rem 0.75rem;
    border: none;
    background: transparent;
    color: var(--foreground);
    cursor: pointer;
    border-radius: var(--radius-md);
    font-size: var(--font-size-sm);
    text-align: left;
    transition: all var(--transition-fast);
  }

  .menu-item:hover {
    background: var(--muted);
  }

  .menu-item:active {
    background: var(--primary);
    color: var(--primary-foreground);
  }

  .menu-item.logout {
    color: var(--destructive);
  }

  .menu-item.logout:hover {
    background: var(--destructive);
    color: var(--destructive-foreground);
  }

  @media (max-width: 640px) {
    .username {
      display: none;
    }

    .menu {
      position: fixed;
      top: auto;
      bottom: 1rem;
      right: 1rem;
      left: 1rem;
      min-width: auto;
    }
  }
</style>

// frontend/src/components/UserMenu.vue
<template>
  <div class="user-menu">
    <button @click="toggleMenu" class="menu-trigger" :class="{ active: isOpen }" ref="triggerRef">
      <div class="avatar">
        <img src="/user.png" alt="用户头像" />
      </div>
    </button>

    <Teleport to="body">
      <Transition name="menu">
        <div v-if="isOpen" class="menu-content" ref="menuRef">
          <div class="menu-header">
            <span class="username">{{ username }}</span>
            <span v-if="user?.role === 'admin'" class="role-badge">管理员</span>
          </div>
          <nav class="menu-items">
            <button @click="handleProfile" class="menu-item">
              <UserCircle :size="18" />
              <span>个人资料</span>
            </button>
            <button @click="handleSettings" class="menu-item">
              <Settings :size="18" />
              <span>设置</span>
            </button>
            <div class="menu-divider"></div>
            <button @click="handleLogout" class="menu-item logout">
              <LogOut :size="18" />
              <span>退出登录</span>
            </button>
          </nav>
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch, nextTick } from 'vue'
import { UserCircle, Settings, LogOut } from 'lucide-vue-next'
import type { User as UserType } from '../types'

interface Props {
  user?: UserType
}

const props = defineProps<Props>()

const emit = defineEmits<{
  profile: []
  settings: []
  logout: []
}>()

const isOpen = ref(false)
const triggerRef = ref<HTMLElement>()
const menuRef = ref<HTMLElement>()
const username = computed(() => props.user?.username || 'Guest')

const toggleMenu = () => {
  isOpen.value = !isOpen.value
  if (isOpen.value) {
    nextTick(() => {
      updateMenuPosition()
    })
  }
}

const updateMenuPosition = () => {
  if (!triggerRef.value || !menuRef.value) return

  const triggerRect = triggerRef.value.getBoundingClientRect()
  const menuWidth = menuRef.value.offsetWidth

  const top = triggerRect.bottom + 8
  const right = window.innerWidth - triggerRect.right

  menuRef.value.style.position = 'fixed'
  menuRef.value.style.top = `${top}px`
  menuRef.value.style.right = `${right}px`
  menuRef.value.style.minWidth = '240px'
}

const handleProfile = () => {
  isOpen.value = false
  emit('profile')
}

const handleSettings = () => {
  isOpen.value = false
  emit('settings')
}

const handleLogout = () => {
  isOpen.value = false
  emit('logout')
}

const handleClickOutside = (e: MouseEvent) => {
  if (isOpen.value && triggerRef.value && !triggerRef.value.contains(e.target as Node) && menuRef.value && !menuRef.value.contains(e.target as Node)) {
    isOpen.value = false
  }
}

const handleEscapeKey = (e: KeyboardEvent) => {
  if (e.key === 'Escape' && isOpen.value) {
    isOpen.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
  document.addEventListener('keydown', handleEscapeKey)
  window.addEventListener('resize', () => {
    if (isOpen.value) {
      updateMenuPosition()
    }
  })
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
  document.removeEventListener('keydown', handleEscapeKey)
})

watch(() => props.user, () => {
  if (isOpen.value) {
    isOpen.value = false
  }
})
</script>

<style scoped>
.user-menu {
  position: relative;
}

.menu-trigger {
  display: flex;
  align-items: center;
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 4px;
  border-radius: var(--radius-full);
  transition: all var(--transition-normal) var(--ease-out);
}

.menu-trigger:hover {
  background: var(--bg-tertiary);
}

.menu-trigger.active .avatar {
  ring: 2px solid var(--color-primary);
}

.avatar {
  width: 36px;
  height: 36px;
  border-radius: var(--radius-full);
  overflow: hidden;
  transition: all var(--transition-normal) var(--ease-out);
}

.avatar img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
</style>

<style>
/* 全局样式，因为 Teleport 到了 body */
.menu-content {
  position: fixed;
  background: var(--glass-bg);
  border: 1px solid var(--glass-border);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-2xl);
  backdrop-filter: blur(var(--glass-blur));
  -webkit-backdrop-filter: blur(var(--glass-blur));
  padding: 8px 0;
  z-index: 99999;
}

.menu-header {
  padding: 12px 16px;
  border-bottom: 1px solid var(--glass-border);
  display: flex;
  align-items: center;
  gap: 8px;
}

.username {
  font-size: var(--font-size-base);
  font-weight: var(--font-weight-semibold);
  color: var(--text-primary);
}

.role-badge {
  padding: 2px 8px;
  background: linear-gradient(135deg, rgba(102, 126, 234, 0.2) 0%, rgba(168, 85, 247, 0.2) 100%);
  border-radius: var(--radius-md);
  font-size: var(--font-size-xs);
  color: var(--color-primary);
}

.menu-items {
  padding: 8px;
  display: flex;
  flex-direction: column;
}

.menu-item {
  display: flex;
  align-items: center;
  gap: 12px;
  width: 100%;
  padding: 12px 16px;
  background: transparent;
  border: none;
  border-radius: var(--radius-md);
  cursor: pointer;
  text-align: left;
  transition: all var(--transition-fast) var(--ease-out);
  color: var(--text-primary);
  font-size: var(--font-size-sm);
}

.menu-item:hover {
  background: var(--hover-bg);
  transform: translateX(-4px);
}

.menu-item svg {
  width: 18px;
  height: 18px;
  flex-shrink: 0;
}

.menu-divider {
  height: 1px;
  background: var(--border-color);
  margin: 4px 0;
}

.menu-item.logout {
  color: var(--color-danger);
}

.menu-item.logout:hover {
  background: rgba(244, 63, 94, 0.1);
}

.menu-enter-active,
.menu-leave-active {
  transition: all var(--transition-normal) var(--ease-out);
}

.menu-enter-from,
.menu-leave-to {
  opacity: 0;
  transform: translateY(-8px) scale(0.95);
}

.menu-enter-to,
.menu-leave-from {
  opacity: 1;
  transform: translateY(0) scale(1);
}

@media (prefers-reduced-motion: reduce) {
  .menu-enter-active,
  .menu-leave-active {
    transition: none;
  }

  .menu-item:hover {
    transform: none;
  }
}
</style>
